Library/Models/Title.cs
namespace Library.Models
{ 
  public class Title
  {
    public int TitleId { get; set; }
    public string Name { get; set; } 
    public List<AuthorTitle> JoinEntities { get; set; }
    public int Copies { get; set; }

    public ApplicationUser User { get; set; }
  }
}

Library/Controllers/TitlesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Library.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Library.Controllers
{
  [Authorize(Roles = "admin, user")]
  public class TitlesController : Controller
  {
    private readonly LibraryContext _db;

    public TitlesController(LibraryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Title> titles = _db.Titles.ToList();
      return View(titles);
    }

    [Authorize(Roles = "admin")]
    public ActionResult Create()
    {
      ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "Name");
      return View();
    }


    [HttpPost]
    public ActionResult Create(Title titles)
    {
      if (!ModelState.IsValid)
      {
        return View(titles);
      }
      else
      {
        _db.Titles.Add(titles);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Title thisTitle = _db.Titles
      .Include(title => title.JoinEntities)
      .ThenInclude(join => join.Author)
      .FirstOrDefault(titles => titles.TitleId == id);
      return View(thisTitle);
    }

    public ActionResult Edit(int id)
    {
      Title thisTitle = _db.Titles.FirstOrDefault(title => title.TitleId == id);
      return View(thisTitle);
    }

    [HttpPost]
    public ActionResult Edit(Title title)
    {
      _db.Titles.Update(title);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
        public ActionResult Delete(int id)
    {
      Title thisTitle = _db.Titles.FirstOrDefault(titles => titles.TitleId == id);
      return View(thisTitle);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Title thisTitle = _db.Titles.FirstOrDefault(title => title.TitleId == id);
      _db.Titles.Remove(thisTitle);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddAuthor(int id)
    {
      Title thisTitle = _db.Titles.FirstOrDefault(titles => titles.TitleId == id);
      ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "Name");
      return View(thisTitle);
    }

    [HttpPost]
    public ActionResult AddAuthor(Title title, int authorId)
    {
        #nullable enable
      AuthorTitle? joinEntity = _db.AuthorTitles.FirstOrDefault(join => (join.AuthorId == authorId && join.TitleId == title.TitleId));
      #nullable disable
      if (joinEntity == null && authorId != 0)
      {
        _db.AuthorTitles.Add(new AuthorTitle() { AuthorId = authorId, TitleId = title.TitleId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = title.TitleId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      AuthorTitle joinEntry = _db.AuthorTitles.FirstOrDefault(entry => entry.AuthorTitleId == joinId);
      _db.AuthorTitles.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    } 
  }
}

Library/Views/Titles/AddAuthor.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Title

<h2>Add an Author</h2>

<h4>Add an Author to this Title: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TitleId)

    @Html.Label("Select Author")
    @Html.DropDownList("AuthorId")

    <input type="submit" value="Save" />
}

Library/Views/Titles/Create.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Title

<h1>Create a Title</h1>

@* @if (@ViewBag.AuthorId.Count == 0)
{
  <p>You must add an Author before creating a title!</p>
}
else
{ *@
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name);
    @Html.TextBoxFor(model => model.Name);<br>
    @Html.LabelFor(model => model.Copies);
    @Html.TextBoxFor(model => model.Copies, new { type="number", min="1", max="100" });
    <br>
    @* @Html.Label("Select Author");
    @Html.DropDownList("AuthorId"); *@
    <br>
    <input type="submit" value="Add a Title"/>
  }
@* } *@

<p>@Html.ActionLink("Back to List", "Index")</p>

Library/Views/Titles/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Title

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}

Library/Views/Titles/Details.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models;
@model Library.Models.Title;


<h1>Title Details</h1>

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Copies): @Html.DisplayFor(model => model.Copies)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Title does not belong to any Authors</p>
}
else
{
  <h4>Author:</h4>
  
  @foreach(AuthorTitle join in Model.JoinEntities)
  {
    <h3>@join.Author.Name</h3>
    @using (Html.BeginForm("DeleteJoin", "Titles"))
    {
      @Html.Hidden("joinId", @join.AuthorTitleId)
      <input type="submit" value="Delete"/>
    }
  }
  
}

<p>@Html.ActionLink("Back to List", "Index")</p>
<p>@Html.ActionLink("Edit this Title", "Edit", new { id = Model.TitleId})</p>
<p>@Html.ActionLink("Delete this Title", "Delete", new { id = Model.TitleId})</p>
<p>@Html.ActionLink("Add an Author", "AddAuthor", new { id = Model.TitleId })</p>

Library/Views/Titles/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Title

<h2>Edit this title</h2>

<h4>Title: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TitleId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}

Library/Views/Titles/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Book Titles</h1>

@using Library.Models;

<h3>List of Titles</h3>

@if (Model.Count == 0)
{
  <h3>No Titles have been added yet</h3>
}
else
{
  <ul>
  @foreach (Title titles in Model)
  {
    <li>@Html.ActionLink($"{titles.Name}", "Details", new { id = titles.TitleId })</li>
  }
  </ul>
}

<p>@Html.ActionLink("Create a new Title", "Create")</p>