Library/Models/Author.cs
namespace Library.Models 
{
  public class Author 
  {
    public int AuthorId { get; set; }
    public string Name { get; set; }
    public List<AuthorTitle> JoinEntities { get; set; }
  }
}

Library/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Library.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Library.Controllers
{
  public class AuthorsController : Controller
  {
    private readonly LibraryContext _db;

    public AuthorsController(LibraryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Author> authors = _db.Authors.ToList();
      return View(authors);
    }

  [Authorize(Roles = "admin")]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Author author)
    {
      if (!ModelState.IsValid)
      {
        return View(author);
      }
      else
      {
        _db.Authors.Add(author);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Author thisAuthor = _db.Authors
      .Include(author => author.JoinEntities)
      .ThenInclude(join => join.Title)
      .FirstOrDefault(author => author.AuthorId == id);
      return View(thisAuthor);
    }

    public ActionResult Edit(int id)
    {
      Author thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
      return View(thisAuthor);
    }

    [HttpPost]
    public ActionResult Edit(Author author)
    {
      _db.Authors.Update(author);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Author thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
      return View(thisAuthor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirm(int id)
    {
      Author thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
      _db.Authors.Remove(thisAuthor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTitle(int id)
    {
      Author thisAuthor = _db.Authors.FirstOrDefault(authors => authors.AuthorId == id);
      ViewBag.TitleId = new SelectList(_db.Titles, "TitleId", "Name");
      return View(thisAuthor);
    }

    [HttpPost]
    public ActionResult AddTitle(Author author, int titleId)
    {
        #nullable enable
      AuthorTitle? joinEntity = _db.AuthorTitles.FirstOrDefault(join => (join.TitleId == titleId && join.AuthorId == author.AuthorId));
      #nullable disable
      if (joinEntity == null && titleId != 0)
      {
        _db.AuthorTitles.Add(new AuthorTitle() { TitleId = titleId, AuthorId = author.AuthorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = author.AuthorId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      AuthorTitle joinEntry = _db.AuthorTitles.FirstOrDefault(entry => entry.AuthorTitleId == joinId);
      _db.AuthorTitles.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    } 
  }
}

Library/Views/Authors/AddTitle.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author

<h2>Add a Title</h2>

<h4>Add a Title to this Author: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.AuthorId)

    @Html.Label("Select Title")
    @Html.DropDownList("TitleId")

    <input type="submit" value="Save" />
}

Library/Views/Authors/Create.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author

<h1>Create an Author</h1>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name);
  @Html.TextBoxFor(model => model.Name);
  <input type="submit" value="Add an author"/>

}
<p>@Html.ActionLink("Back to List", "Index")</p>

Library/Views/Authors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-danger"/>
}
@Html.ActionLink("Back to List", "Index")

Library/Views/Authors/Details.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author;
@using Library.Models;


<h1>Author Details</h1>

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This Author has no Titles</p>
}
else
{
  <h4>Titles:</h4>
  
  @foreach(AuthorTitle join in Model.JoinEntities)
  {
    <h3>@join.Title.Name | Copies: @join.Title.Copies</h3>
    @using (Html.BeginForm("DeleteJoin", "Authors"))
    {
      @Html.Hidden("joinId", @join.AuthorTitleId)
      <input type="submit" value="Delete"/>
    }
  }
  
}

<p>@Html.ActionLink("Add a Title", "AddTitle", new { id = Model.AuthorId})</p>
<p>@Html.ActionLink("Back to List", "Index")</p>
<p>@Html.ActionLink("Edit this Author", "Edit", new { id = Model.AuthorId })</p>
<p>@Html.ActionLink("Delete this Author", "Delete", new { id = Model.AuthorId })</p>

Library/Views/Authors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Author

<h2>Edit</h2>

<h4>Edit this Author: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.AuthorId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Library/Views/Authors/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Authors</h1>

@using Library.Models;

<h3>List of Authors</h3>

@if (Model.Count == 0)
{
  <h3>No authors have been added yet</h3>
}
else
{
  <ul>
  @foreach (Author author in Model)
  {
    <li>@Html.ActionLink($"{author.Name}", "Details", new { id = author.AuthorId })</li>
  }
  </ul>
}

<p>@Html.ActionLink("Create a new Author", "Create")</p>